name: flutter_application_3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
  animated_text_kit: ^4.2.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 📌 Sección para los archivos de imágenes
  assets:
    - assets/Fondo_Login.jpg  # ✅ Imagen de fondo (asegúrate de que el archivo existe)

  # 📌 Sección para los archivos de fuentes personalizadas
  fonts:
    - family: SportsWorld
      fonts:
        - asset: assets/fonts/Sports World-Regular.ttf  # ✅ Fuente personalizada
